USE PROGRU
GO

CREATE TABLE CANDIDATO (
COD_CANDIDATO int identity (1,1) PRIMARY KEY,
LOGINN varchar(50) NOT NULL,
SENHA varchar(8) NOT NULL,
NOME varchar(50)NOT NULL,
TELEFONE varchar (15) NOT NULL,
EMAIL varchar(50)NOT NULL,
ENDERECO varchar (100),
OBJETIVO varchar(20)NOT NULL,
CIDADE varchar(20)NOT NULL,
ESTADO varchar(20)NOT NULL,
CURRICULO_DOC varchar
)
GO

CREATE TABLE EMPRESA (
COD_EMPRESA int identity (1,1) PRIMARY KEY,
LOGINN varchar(50) NOT NULL,
SENHA varchar(8)NOT NULL,
NOME varchar(50)NOT NULL,
RAMO varchar(50),
ENDERECO varchar (100),
CIDADE varchar(20)NOT NULL,
ESTADO varchar(20)NOT NULL,
EMAIL varchar(50)NOT NULL,
TELEFONE varchar (15)NOT NULL
)
GO

CREATE TABLE VAGAS_EMPREGO (
COD_VAGA int identity (1,1) PRIMARY KEY,
COD_EMPRESA int NOT NULL,
DESCRICAO varchar(500) NOT NULL,
REMUNERACAO money NOT NULL,
CARGO varchar(50) NOT NULL,
ENDERECO varchar (100),
CIDADE varchar(20) NOT NULL,
ESTADO varchar(20) NOT NULL,
EMAIL varchar(50) NOT NULL,
FOREIGN KEY(COD_EMPRESA) REFERENCES EMPRESA (COD_EMPRESA)
)
GO

CREATE TABLE CURSOS (
COD_CURSO int identity (1,1) PRIMARY KEY,
COD_EMPRESA int NOT NULL,
NOME_CURSO varchar(50) NOT NULL,
CARGA_HORARIA varchar(8) NOT NULL,
TELEFONE varchar (15) NOT NULL,
DESCRICAO varchar(500),
FOREIGN KEY(COD_EMPRESA) REFERENCES EMPRESA (COD_EMPRESA)
)
GO
